version: "3"

services:
  postgres:
    container_name: postgres
    image: 'postgres:14-alpine'
    environment: 
      POSTGRES_DB: '${TG_BOT_DB:-tg_bot}'
      POSTGRES_USER: '${TG_BOT_DB_USER:-tg_bot_user}'
      POSTGRES_PASSWORD: '${TG_BOT_DB_PASSWORD:-secret}'
      PGDATA: '/var/lib/postgresql/data'
    ports: 
      - '${TG_BOT_DB_PORT:-5432}:5432'
    volumes:
      - tg_bot_postgres:/var/lib/postgresql/data

  filed:
    container_name: file_d
    command: /file.d/file.d --config /config.yaml
    image: ozonru/file.d:latest-linux-amd64
    volumes:
      - ../logs/:/tmp/logs
      - ../build/file_d/config.yml:/config.yaml:ro
    links:
      - graylog
    depends_on:
      - graylog
      
  mongodb:
    container_name: mongodb
    image: mongo:3
    volumes:
      - tg_bot_mongo:/data/db

  elasticsearch:
    container_name: elasticsearch
    image: elasticsearch:7.17.6
    volumes:
      - tg_bot_elastic:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"

  graylog:
    container_name: graylog
    image: graylog/graylog:4.3
    volumes:
      - ../build/graylog/config.conf:/usr/share/graylog/data/config/graylog.conf:ro
    environment:
      # (must be at least 16 characters)
      - GRAYLOG_PASSWORD_SECRET=EabOdthinPafivup
      # Password: admin
      - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
      - GRAYLOG_HTTP_BIND_ADDRESS=0.0.0.0:7555
      - GRAYLOG_HTTP_EXTERNAL_URI=http://127.0.0.1:7555/
    links:
      - mongodb:mongo
      - elasticsearch
    depends_on:
      - mongodb
      - elasticsearch
    ports:
      # Graylog web interface and REST API
      - 7555:7555
      # Syslog TCP
      - 8514:8514
      # Syslog UDP
      - 8514:8514/udp
      # GELF TCP
      - 12201:12201

  prometheus:
    container_name: prometheus
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ../build/prometheus/config.yml:/etc/prometheus/prometheus.yml:ro
      - ../build/prometheus/alerts.yml:/etc/prometheus/alerts.yml:ro
    extra_hosts:
      - "host.docker.internal:host-gateway"

  grafana:
    container_name: grafana
    image: grafana/grafana-oss
    ports:
      - 3000:3000
    volumes:
      - tg_bot_grafana:/var/lib/grafana
    links:
      - prometheus

  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.18
    ports:
      - 5775:5775/udp
      - 6831:6831/udp
      - 6832:6832/udp
      - 5778:5778
      - 16686:16686 # web
      - 14268:14268
      - 9411:9411


volumes:
  tg_bot_postgres:
    name: 'tg-bot-postgres'
  tg_bot_mongo:
    name: 'tg-bot-mongo'
  tg_bot_elastic:
    name: 'tg-bot-elastic'
  tg_bot_grafana:
    name: 'tg-bot-grafana'