version: "3"

services:
  postgres:
    container_name: postgres
    image: 'postgres:14-alpine'
    environment: 
      POSTGRES_DB: '${TG_BOT_DB:-tg_bot}'
      POSTGRES_USER: '${TG_BOT_DB_USER:-tg_bot_user}'
      POSTGRES_PASSWORD: '${TG_BOT_DB_PASSWORD:-secret}'
      PGDATA: '/var/lib/postgresql/data'
    ports: 
      - '${TG_BOT_DB_PORT:-5432}:5432'
    volumes:
        - tg_bot_postgres:/var/lib/postgresql/data

volumes:
  tg_bot_postgres:
    name: 'tg-bot-postgres'