// Code generated by protoc-gen-validate. DO NOT EDIT.
// source: Reporter.proto

package api

import (
	"bytes"
	"errors"
	"fmt"
	"net"
	"net/mail"
	"net/url"
	"regexp"
	"sort"
	"strings"
	"time"
	"unicode/utf8"

	"google.golang.org/protobuf/types/known/anypb"
)

// ensure the imports are used
var (
	_ = bytes.MinRead
	_ = errors.New("")
	_ = fmt.Print
	_ = utf8.UTFMax
	_ = (*regexp.Regexp)(nil)
	_ = (*strings.Reader)(nil)
	_ = net.IPv4len
	_ = time.Duration(0)
	_ = (*url.URL)(nil)
	_ = (*mail.Address)(nil)
	_ = anypb.Any{}
	_ = sort.Sort
)

// Validate checks the field values on SendReportRequest with the rules defined
// in the proto definition for this message. If any rules are violated, the
// first error encountered is returned, or nil if there are no violations.
func (m *SendReportRequest) Validate() error {
	return m.validate(false)
}

// ValidateAll checks the field values on SendReportRequest with the rules
// defined in the proto definition for this message. If any rules are
// violated, the result is a list of violation errors wrapped in
// SendReportRequestMultiError, or nil if none found.
func (m *SendReportRequest) ValidateAll() error {
	return m.validate(true)
}

func (m *SendReportRequest) validate(all bool) error {
	if m == nil {
		return nil
	}

	var errors []error

	// no validation rules for Rows

	// no validation rules for UserId

	// no validation rules for Period

	if len(errors) > 0 {
		return SendReportRequestMultiError(errors)
	}

	return nil
}

// SendReportRequestMultiError is an error wrapping multiple validation errors
// returned by SendReportRequest.ValidateAll() if the designated constraints
// aren't met.
type SendReportRequestMultiError []error

// Error returns a concatenation of all the error messages it wraps.
func (m SendReportRequestMultiError) Error() string {
	var msgs []string
	for _, err := range m {
		msgs = append(msgs, err.Error())
	}
	return strings.Join(msgs, "; ")
}

// AllErrors returns a list of validation violation errors.
func (m SendReportRequestMultiError) AllErrors() []error { return m }

// SendReportRequestValidationError is the validation error returned by
// SendReportRequest.Validate if the designated constraints aren't met.
type SendReportRequestValidationError struct {
	field  string
	reason string
	cause  error
	key    bool
}

// Field function returns field value.
func (e SendReportRequestValidationError) Field() string { return e.field }

// Reason function returns reason value.
func (e SendReportRequestValidationError) Reason() string { return e.reason }

// Cause function returns cause value.
func (e SendReportRequestValidationError) Cause() error { return e.cause }

// Key function returns key value.
func (e SendReportRequestValidationError) Key() bool { return e.key }

// ErrorName returns error name.
func (e SendReportRequestValidationError) ErrorName() string {
	return "SendReportRequestValidationError"
}

// Error satisfies the builtin error interface
func (e SendReportRequestValidationError) Error() string {
	cause := ""
	if e.cause != nil {
		cause = fmt.Sprintf(" | caused by: %v", e.cause)
	}

	key := ""
	if e.key {
		key = "key for "
	}

	return fmt.Sprintf(
		"invalid %sSendReportRequest.%s: %s%s",
		key,
		e.field,
		e.reason,
		cause)
}

var _ error = SendReportRequestValidationError{}

var _ interface {
	Field() string
	Reason() string
	Key() bool
	Cause() error
	ErrorName() string
} = SendReportRequestValidationError{}
