// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.7
// source: Reporter.proto

package api

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ReporterV1Client is the client API for ReporterV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ReporterV1Client interface {
	SendReport(ctx context.Context, in *SendReportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error)
}

type reporterV1Client struct {
	cc grpc.ClientConnInterface
}

func NewReporterV1Client(cc grpc.ClientConnInterface) ReporterV1Client {
	return &reporterV1Client{cc}
}

func (c *reporterV1Client) SendReport(ctx context.Context, in *SendReportRequest, opts ...grpc.CallOption) (*emptypb.Empty, error) {
	out := new(emptypb.Empty)
	err := c.cc.Invoke(ctx, "/ReporterV1.ReporterV1/SendReport", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ReporterV1Server is the server API for ReporterV1 service.
// All implementations must embed UnimplementedReporterV1Server
// for forward compatibility
type ReporterV1Server interface {
	SendReport(context.Context, *SendReportRequest) (*emptypb.Empty, error)
	mustEmbedUnimplementedReporterV1Server()
}

// UnimplementedReporterV1Server must be embedded to have forward compatible implementations.
type UnimplementedReporterV1Server struct {
}

func (UnimplementedReporterV1Server) SendReport(context.Context, *SendReportRequest) (*emptypb.Empty, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendReport not implemented")
}
func (UnimplementedReporterV1Server) mustEmbedUnimplementedReporterV1Server() {}

// UnsafeReporterV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ReporterV1Server will
// result in compilation errors.
type UnsafeReporterV1Server interface {
	mustEmbedUnimplementedReporterV1Server()
}

func RegisterReporterV1Server(s grpc.ServiceRegistrar, srv ReporterV1Server) {
	s.RegisterService(&ReporterV1_ServiceDesc, srv)
}

func _ReporterV1_SendReport_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ReporterV1Server).SendReport(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ReporterV1.ReporterV1/SendReport",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ReporterV1Server).SendReport(ctx, req.(*SendReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ReporterV1_ServiceDesc is the grpc.ServiceDesc for ReporterV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ReporterV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ReporterV1.ReporterV1",
	HandlerType: (*ReporterV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendReport",
			Handler:    _ReporterV1_SendReport_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "Reporter.proto",
}
