token:

storage:
  mode: "memory" # "sql"

database:
  dsn: postgres://tg_bot_user:secret@localhost:5432/tg_bot

logger:
  level: "debug" # info, warn, error, fatal

metrics:
  url: "/metrics"
  port: 8080

cache:
  mode: "memory" # redis
  length: 10 # только для memory кеша

redis:
  addr: "localhost:6379"
  password: ""
  db: 0