token:

storage:
  mode: "memory" # "sql"

database:
  dsn: postgres://tg_bot_user:secret@localhost:5432/tg_bot

logger:
  level: "debug" # info, warn, error, fatal

metrics:
  url: "/metrics"
  port: 8080